In [9]:
import numpy as np
import time

## Creating Array

In [10]:
arr_1d = np.array([1, 2, 3 , 4 , 5 , 6 , 7])
print(arr_1d)

arr_2d = np.array([[1 , 2 , 3], [4 , 5 , 6]])
print(arr_2d)

[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]]


## List vs NumPy array

In [11]:
py_list = [1, 2 , 3]
print("Python list multiplication : ",py_list)

np_array = np.array([1 , 2 , 3]) ## Element wise multiplication 
print("Python array multiplication : ", np_array * 2)

start_time = time.time()
py_list = [i * 2 for i in range(10000)]
print("\n List operation time : ", time.time() - start_time)

start_time = time.time()
np_array = np.arange(100000)
print("\n Numpy operation time : ", time.time() - start_time)

Python list multiplication :  [1, 2, 3]
Python array multiplication :  [2 4 6]

 List operation time :  0.0009872913360595703

 Numpy operation time :  0.0008373260498046875


## Creating Array from Scratch

In [12]:
zeros = np.zeros((3,4))
print("Zeros Array : \n",zeros)

ones = np.ones((2,3))
print("Ones Array : \n",ones)

full = np.full((2,2),5) ## Constant Variable
print("full Array : \n",full)

## Random values array 

randoms = np.random.random((2,3)) ## 2 by 3 matrices with Random values
print("Random Array : \n",randoms)

## Sequence Array

sequence = np.arange(0,20,2)
print("Sequence Array : \n",sequence)

Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
full Array : 
 [[5 5]
 [5 5]]
Random Array : 
 [[0.87968666 0.08128112 0.96560351]
 [0.80610181 0.07426553 0.59896294]]
Sequence Array : 
 [ 0  2  4  6  8 10 12 14 16 18]


## Vector , Matrices , Tensor

In [13]:
vector = np.array((1,2,3))
print("Vector :",vector)

matrices = np.array([[1 , 2 , 3],
                     [4 , 5 , 6]])
print("Matrices :",matrices)

tensor = np.array([[[1 , 2] , [3 , 4]],
                   [[5 , 6] , [7 , 8]]])
print("Tensor :",tensor)

Vector : [1 2 3]
Matrices : [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array Properties

In [14]:
arr = np.array([[1 , 2 , 3],
                [4 , 5 , 6]])
print("Shape : ", arr.shape) # Array Shape
print("Dimension : ", arr.ndim) # Array Dimension
print("Size : ", arr.size) # Size of Array
print("Data type : ",arr.dtype) # Data Type

Shape :  (2, 3)
Dimension :  2
Size :  6
Data type :  int64


# ReShaped Array

In [20]:
arr = np.arange(12)
print("Original array : ",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array : \n", reshaped)

# faltten ( returns a new copy of the original array collapsed into one dimension)
flattened = reshaped.flatten()
print("\n Flattened array : ",flattened)

# ravel (return view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled Array : ",raveled)

# Transpose

transpose = reshaped.T
print("\n Transposed array : ", transpose)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
