In [9]:
import numpy as np
import time

## Creating Array

In [10]:
arr_1d = np.array([1, 2, 3 , 4 , 5 , 6 , 7])
print(arr_1d)

arr_2d = np.array([[1 , 2 , 3], [4 , 5 , 6]])
print(arr_2d)

[1 2 3 4 5 6 7]
[[1 2 3]
 [4 5 6]]


## List vs NumPy array

In [11]:
py_list = [1, 2 , 3]
print("Python list multiplication : ",py_list)

np_array = np.array([1 , 2 , 3]) ## Element wise multiplication 
print("Python array multiplication : ", np_array * 2)

start_time = time.time()
py_list = [i * 2 for i in range(10000)]
print("\n List operation time : ", time.time() - start_time)

start_time = time.time()
np_array = np.arange(100000)
print("\n Numpy operation time : ", time.time() - start_time)

Python list multiplication :  [1, 2, 3]
Python array multiplication :  [2 4 6]

 List operation time :  0.001146554946899414

 Numpy operation time :  0.0005142688751220703


## Creating Array from Scratch

In [12]:
zeros = np.zeros((3,4))
print("Zeros Array : \n",zeros)

ones = np.ones((2,3))
print("Ones Array : \n",ones)

full = np.full((2,2),5) ## Constant Variable
print("full Array : \n",full)

## Random values array 

randoms = np.random.random((2,3)) ## 2 by 3 matrices with Random values
print("Random Array : \n",randoms)

## Sequence Array

sequence = np.arange(0,20,2)
print("Sequence Array : \n",sequence)

Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
full Array : 
 [[5 5]
 [5 5]]
Random Array : 
 [[0.59057292 0.47023074 0.78659885]
 [0.8637176  0.07747739 0.22112955]]
Sequence Array : 
 [ 0  2  4  6  8 10 12 14 16 18]


## Vector , Matrices , Tensor

In [13]:
vector = np.array((1,2,3))
print("Vector :",vector)

matrices = np.array([[1 , 2 , 3],
                     [4 , 5 , 6]])
print("Matrices :",matrices)

tensor = np.array([[[1 , 2] , [3 , 4]],
                   [[5 , 6] , [7 , 8]]])
print("Tensor :",tensor)

Vector : [1 2 3]
Matrices : [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array Properties

In [ ]:
arr = np.array([[1 , 2 , 3],
                [4 , 5 , 6]])
print("Shape : ", arr.shape) # Array Shape
print("Dimension : ", arr.ndim) # Array Dimension
print("Size : ", arr.size) # Size of Array
print("Data type : ",arr.dtype) # Data Tyep